import Head from "next/head";
import MainPageTop from "../components/mainPage/MainPageTop";
import MainPageExplore from "../components/mainPage/MainPageExplore";
import MainPageAttractions from "../components/mainPage/MainPageAttractions";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Travel The Philippines</title>
        <meta
          name="Everything you need to know about the Philippines"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-5xl mx-auto ">
        <MainPageTop />
        <MainPageExplore />
        <MainPageAttractions />
      </main>
    </div>
  );
}
